train_datasets:
  - dataset: "ivrit-ai/audio-labeled"
    name: "default"
    split: "train"
    input_fields:
      - "audio"
      - "text"

eval_datasets:
  - dataset: "ivrit-ai/audio-labeled"
    name: "default"
    split: "test"
    input_fields:
      - "audio"
      - "text"

preprocessing:
  text:
    remove_special_characters: True
    lowercase: False
    remove_punctuation: True
    remove_latin_characters: True
    only_hebrew_letters: True

pretrained_model: "facebook/w2v-bert-2.0"
train_batch_size: 16
eval_batch_size: 4
num_workers: 32
debug: False
result_path: "results"
exp_name: "hebrew"
sampling_rate: 16000
warmup_steps: 1000
learning_rate: 5e-5
save_steps: 1000
eval_steps: 500
logging_steps: 500
save_total_limit: 2
push_to_hub: False
gradient_checkpointing: True
train_epochs: 10
gradient_accumulation_steps: 2
