train_datasets:
  - dataset: "ivrit-ai/crowd-transcribe-v1"
    name: "default"
    split: "train"
    input_fields:
      - "audio"
      - "sentence"

eval_datasets:
  - dataset: "ivrit-ai/crowd-transcribe-v1"
    name: "default"
    split: "test"
    input_fields:
      - "audio"
      - "sentence"

preprocessing:
  text:
    remove_special_characters: True
    lowercase: False
    remove_punctuation: True
    remove_latin_characters: True
    only_hebrew_letters: True

pretrained_model: "facebook/w2v-bert-2.0"
train_batch_size: 12
eval_batch_size: 12
num_workers: 32
debug: False
result_path: "results"
exp_name: "hebrew-crowd-transcribe-v1"
sampling_rate: 16000
warmup_steps: 4000
learning_rate: 5e-5
save_steps: 10000
eval_steps: 10000
logging_steps: 1500
save_total_limit: 3
push_to_hub: False
gradient_checkpointing: True
train_epochs: 10
gradient_accumulation_steps: 2
resume_from_checkpoint: False
